/**
 * Local Worker lifecycle, shared by `functional-test.mjs` and
 * `tests/browser.test.js` so neither grows its own copy.
 *
 * The reason this is a real process rather than a mock: the bugs that actually
 * broke this app — Cloudflare's PBKDF2 iteration ceiling, a Durable Object rate
 * limit, a missing binding — only reproduce inside the Workers runtime.
 */
import { spawn, execFileSync } from 'node:child_process';
import { existsSync, rmSync, writeFileSync } from 'node:fs';
import { setTimeout as delay } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const projectDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const devVarsPath = join(projectDir, '.dev.vars');

/**
 * A throwaway local secret file so `wrangler dev` has every binding it expects.
 *
 * `AUTH_PEPPER` is the only secret the app has: it sends no email, so there is no
 * mail API key to provide and no provider that can be misconfigured.
 */
function writeLocalDevVars(source) {
  if (existsSync(devVarsPath)) return false;
  writeFileSync(devVarsPath, [
    `# Generated by ${source} for a hermetic local run.`,
    'AUTH_PEPPER=local-functional-test-pepper-0123456789abcdef',
    '# The local Durable Object keeps its rate-limit counters in .wrangler/state,',
    '# which persists between runs. Without this the suite rate-limits itself after',
    '# roughly ten sign-in attempts, and later runs fail for a reason that has',
    '# nothing to do with the code under test.',
    'RATE_LIMIT_ALLOWLIST=127.0.0.1',
    ''
  ].join('\n'));
  return true;
}

function runWrangler(args) {
  return execFileSync('npx', ['wrangler', ...args], { cwd: projectDir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

/**
 * Start `wrangler dev` and wait until it answers. Returns a stop function.
 * Always call it, or a failed run leaves a listener holding the port.
 */
export async function startLocalWorker({ port = 8788, source = 'the test suite' } = {}) {
  const origin = `http://127.0.0.1:${port}`;
  if (writeLocalDevVars(source)) console.log('  (created a temporary .dev.vars for this run)');
  runWrangler(['d1', 'migrations', 'apply', 'financial-tracking', '--local']);
  const devProcess = spawn('npx', ['wrangler', 'dev', '--port', String(port), '--local', '--ip', '127.0.0.1'], {
    cwd: projectDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    // A process group lets stop() take down workerd and every other child.
    detached: true,
    env: { ...process.env, WRANGLER_SEND_METRICS: 'false' }
  });
  let log = '';
  devProcess.stdout.on('data', (chunk) => { log += chunk; });
  devProcess.stderr.on('data', (chunk) => { log += chunk; });
  devProcess.on('exit', (code) => {
    if (code) console.error(`\nwrangler dev output:\n${log.slice(-2000)}`);
  });

  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    if (devProcess.exitCode !== null && devProcess.exitCode !== undefined) {
      throw new Error(`wrangler dev exited early with code ${devProcess.exitCode}`);
    }
    try {
      if ((await fetch(`${origin}/api/health`)).ok) break;
    } catch {
      /* not listening yet */
    }
    await delay(500);
    if (Date.now() >= deadline) throw new Error(`Worker did not become ready at ${origin} within 60s`);
  }

  return {
    origin,
    stop() {
      devProcess.kill('SIGTERM');
      // A leftover .dev.vars would shadow the developer's real secrets.
      try { rmSync(devVarsPath, { force: true }); } catch { /* best effort */ }
    }
  };
}
